/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const ReadingLazyRouteImport = createFileRoute('/reading')()
const NatalChartLazyRouteImport = createFileRoute('/natal-chart')()
const DashboardLazyRouteImport = createFileRoute('/dashboard')()
const IndexLazyRouteImport = createFileRoute('/')()
const ReadingIndexLazyRouteImport = createFileRoute('/reading/')()
const ReadingDetailLazyRouteImport = createFileRoute('/reading/detail')()

const ReadingLazyRoute = ReadingLazyRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/reading.lazy').then((d) => d.Route))
const NatalChartLazyRoute = NatalChartLazyRouteImport.update({
  id: '/natal-chart',
  path: '/natal-chart',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/natal-chart.lazy').then((d) => d.Route))
const DashboardLazyRoute = DashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ReadingIndexLazyRoute = ReadingIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReadingLazyRoute,
} as any).lazy(() => import('./routes/reading.index.lazy').then((d) => d.Route))
const ReadingDetailLazyRoute = ReadingDetailLazyRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => ReadingLazyRoute,
} as any).lazy(() =>
  import('./routes/reading.detail.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/natal-chart': typeof NatalChartLazyRoute
  '/reading': typeof ReadingLazyRouteWithChildren
  '/reading/detail': typeof ReadingDetailLazyRoute
  '/reading/': typeof ReadingIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/natal-chart': typeof NatalChartLazyRoute
  '/reading/detail': typeof ReadingDetailLazyRoute
  '/reading': typeof ReadingIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/natal-chart': typeof NatalChartLazyRoute
  '/reading': typeof ReadingLazyRouteWithChildren
  '/reading/detail': typeof ReadingDetailLazyRoute
  '/reading/': typeof ReadingIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/natal-chart'
    | '/reading'
    | '/reading/detail'
    | '/reading/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/natal-chart' | '/reading/detail' | '/reading'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/natal-chart'
    | '/reading'
    | '/reading/detail'
    | '/reading/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DashboardLazyRoute: typeof DashboardLazyRoute
  NatalChartLazyRoute: typeof NatalChartLazyRoute
  ReadingLazyRoute: typeof ReadingLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natal-chart': {
      id: '/natal-chart'
      path: '/natal-chart'
      fullPath: '/natal-chart'
      preLoaderRoute: typeof NatalChartLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/': {
      id: '/reading/'
      path: '/'
      fullPath: '/reading/'
      preLoaderRoute: typeof ReadingIndexLazyRouteImport
      parentRoute: typeof ReadingLazyRoute
    }
    '/reading/detail': {
      id: '/reading/detail'
      path: '/detail'
      fullPath: '/reading/detail'
      preLoaderRoute: typeof ReadingDetailLazyRouteImport
      parentRoute: typeof ReadingLazyRoute
    }
  }
}

interface ReadingLazyRouteChildren {
  ReadingDetailLazyRoute: typeof ReadingDetailLazyRoute
  ReadingIndexLazyRoute: typeof ReadingIndexLazyRoute
}

const ReadingLazyRouteChildren: ReadingLazyRouteChildren = {
  ReadingDetailLazyRoute: ReadingDetailLazyRoute,
  ReadingIndexLazyRoute: ReadingIndexLazyRoute,
}

const ReadingLazyRouteWithChildren = ReadingLazyRoute._addFileChildren(
  ReadingLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DashboardLazyRoute: DashboardLazyRoute,
  NatalChartLazyRoute: NatalChartLazyRoute,
  ReadingLazyRoute: ReadingLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
